In [39]:
# import the package
import tensorflow as tf
from tensorflow.keras.datasets import cifar10 
import numpy as np 

In [40]:
# split the train and test set
(X_train , y_train) , (X_test , y_test) = cifar10.load_data()

In [41]:
X_train.shape 

(50000, 32, 32, 3)

In [42]:
y_train[:5] # it a two dimension array but 
# we want only index of classes value like
#  6 is frog etc so reshape it

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [43]:
classes = ["airplane", "automobile" , "bird" , "cat" , "deer" , "dog" , "frog" , "horse" , "ship" , "truck"]

In [44]:
import matplotlib.pyplot as plt 

def plot_sample(X , y , index):
    plt.figure(figsize=(15 , 2))
    plt.imshow(X[index])
    plt.xlabel(classes[y[index]])

plot_sample(X_train , y_train , 53)

In [46]:
# Normalize the data
X_train = X_train / 255
X_test = X_test / 255

In [47]:
# Build a model
from tensorflow.keras.layers import Conv2D , MaxPooling2D , Flatten , Dense , Dropout
from tensorflow.keras.models import Sequential

model = Sequential([
    Conv2D(32 , (3,3) , activation="relu" ,input_shape = (32,32,3)),
    MaxPooling2D(pool_size= (2,2)),

    Conv2D(64 , (3,3) , activation="relu"),
    MaxPooling2D(pool_size= (2,2)),

    Conv2D(64 , (3,3) , activation="relu"),
    MaxPooling2D(pool_size= (2,2)),

    Flatten(),
    Dense(64 , activation="relu"),
    Dense(10  ,activation="softmax")
])

In [48]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 4, 4, 64)          36928     
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 2, 2, 64)          0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 256)              

In [49]:
# compile the model
model.compile(optimizer="adam" , loss="sparse_categorical_crossentropy" , metrics=["accuracy"])

In [50]:
# train the model
model.fit(X_train , y_train , epochs=10 , validation_data=(X_test , y_test))

Epoch 1/10
1563/1563 [==============================] - 6s 4ms/step - loss: 1.8095 - accuracy: 0.3305 - val_loss: 1.3272 - val_accuracy: 0.5275
Epoch 2/10
1563/1563 [==============================] - 5s 3ms/step - loss: 1.2377 - accuracy: 0.5597 - val_loss: 1.1283 - val_accuracy: 0.5997
Epoch 3/10
1563/1563 [==============================] - 5s 3ms/step - loss: 1.0747 - accuracy: 0.6228 - val_loss: 1.0749 - val_accuracy: 0.6243
Epoch 4/10
1563/1563 [==============================] - 5s 3ms/step - loss: 0.9620 - accuracy: 0.6643 - val_loss: 0.9905 - val_accuracy: 0.6583
Epoch 5/10
1563/1563 [==============================] - 5s 3ms/step - loss: 0.8921 - accuracy: 0.6899 - val_loss: 0.9402 - val_accuracy: 0.6754
Epoch 6/10
1563/1563 [==============================] - 6s 4ms/step - loss: 0.8245 - accuracy: 0.7140 - val_loss: 0.9034 - val_accuracy: 0.6972
Epoch 7/10
1563/1563 [==============================] - 5s 3ms/step - loss: 0.7659 - accuracy: 0.7346 - val_loss: 0.9522 - val_accuracy:

In [56]:
model.evaluate(X_test , y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.8766 - accuracy: 0.7001


[0.8766219019889832, 0.7001000046730042]

In [52]:
y_pred = model.predict(X_test)
y_pred[:4]

array([[2.1483644e-03, 7.7203140e-03, 1.4289965e-04, 6.3389575e-01,
        1.5119778e-03, 3.2665667e-01, 7.9587884e-03, 1.3293640e-03,
        1.5487095e-02, 3.1488484e-03],
       [5.2712921e-02, 1.4766584e-01, 8.4593682e-07, 2.3238830e-05,
        4.2195838e-06, 2.2175131e-07, 1.0044594e-07, 1.5454458e-06,
        7.4206144e-01, 5.7529692e-02],
       [3.7096400e-02, 6.2614895e-02, 2.0734790e-04, 2.1912209e-03,
        4.6872173e-04, 1.3378999e-04, 6.0228009e-05, 8.4766471e-05,
        7.3628277e-01, 1.6085985e-01],
       [9.3692636e-01, 2.4043836e-03, 6.8668071e-03, 2.6576500e-03,
        8.4198210e-03, 2.9075793e-05, 7.9400714e-05, 2.6923983e-04,
        4.2250246e-02, 9.6993732e-05]], dtype=float32)

In [53]:
y_classes = [np.argmax(element) for element in y_pred]
y_classes[:5]

[3, 8, 8, 0, 6]

In [54]:
y_test = y_test.reshape(-1,)
y_test[:5]

array([3, 8, 8, 0, 6], dtype=uint8)

In [57]:
# save the model

model.save("imagemodel.h5")